import { Router } from 'express';
import bcrypt from 'bcryptjs';
import PDFDocument from 'pdfkit';
import { v4 as uuid } from 'uuid';
import { randomInt } from 'node:crypto';
import { z } from 'zod';
import { authenticate, allow } from '../middleware/auth.js';
import { readDb, mutateDb, backupDb } from '../repositories/jsonRepository.js';
import { audit, notify } from '../services/audit.js';
import { hasRole,getOrder,changeStatus,checkOrder,createInvoiceAndTransport } from '../services/workflow.js';
import { answerFor } from '../ai/agent.js';
import { AppError } from '../utils/errors.js';
import { config } from '../config/env.js';
const r=Router();r.use(authenticate);
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const ok=(res,data,message='Amal bajarildi',meta={})=>res.json({success:true,message,data,meta});
const byId=(arr,id,label='Maʼlumot')=>{const x=arr.find(v=>v.id===id);if(!x)throw new AppError(`${label} topilmadi`,404);return x;};
const roles={admin:['admin'],coord:['admin','coordinator'],coordinator:['admin','coordinator'],warehouse:['admin','warehouse'],supply:['admin','supply'],logistics:['admin','logistics'],ops:['admin','warehouse','coordinator','supply','logistics']};
const userSafe=u=>{const {passwordHash,...safe}=u;return safe;};
function visibleOrders(db,user){return user.role==='coordinator'?db.orders.filter(o=>o.coordinatorId===user.id):db.orders;}
function orderView(db,o){return {...o,object:db.objects.find(x=>x.id===o.objectId),coordinator:userSafe(db.users.find(x=>x.id===o.coordinatorId)||{}),items:db.orderItems.filter(x=>x.orderId===o.id).map(i=>({...i,product:db.products.find(p=>p.id===i.productId)})),supplyRequests:db.supplyRequests.filter(x=>x.orderId===o.id),invoice:db.invoices.find(x=>x.orderId===o.id),transport:db.transportRequests.find(x=>x.orderId===o.id),shipment:db.shipments.find(x=>x.orderId===o.id)};}
const filterList=(data,req)=>{let rows=[...data];const q=String(req.query.q||'').toLowerCase();if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));for(const k of ['status','role','categoryId','warehouseId','orderId'])if(req.query[k])rows=rows.filter(x=>x[k]===req.query[k]);const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||50));return {rows:rows.slice((page-1)*limit,page*limit),meta:{total:rows.length,page,limit}};};

// Dashboard is computed from current persisted records; coordinator scope stays private.
r.get('/dashboard/summary',wrap(async(req,res)=>{const db=await readDb(),orders=visibleOrders(db,req.user),active=orders.filter(o=>!['delivered','cancelled'].includes(o.status)),today=new Date().toISOString().slice(0,10),low=db.products.filter(p=>p.quantity-p.reservedQuantity<=p.minimumQuantity),mineShipments=db.shipments.filter(s=>orders.some(o=>o.id===s.orderId));ok(res,{products:db.products.length,totalUnits:db.products.reduce((s,p)=>s+p.quantity,0),availableUnits:db.products.reduce((s,p)=>s+p.quantity-p.reservedQuantity,0),reservedUnits:db.products.reduce((s,p)=>s+p.reservedQuantity,0),lowStock:low.length,newOrders:orders.filter(o=>o.status==='new').length,inProgress:active.length,shortages:db.shortages.filter(s=>req.user.role==='coordinator'?orders.some(o=>o.id===s.orderId):s.status==='open').length,supplyInProgress:db.supplyRequests.filter(s=>!['received','cancelled'].includes(s.status)&&(req.user.role!=='coordinator'||orders.some(o=>o.id===s.orderId))).length,readyForLoading:orders.filter(o=>o.status==='ready_for_loading').length,waitingTransport:orders.filter(o=>o.status==='waiting_transport').length,shippedToday:mineShipments.filter(s=>s.shippedAt?.slice(0,10)===today).length,lateOrders:active.filter(o=>o.requiredDate<today).length,deliveredToday:mineShipments.filter(s=>s.deliveredAt?.slice(0,10)===today).length,orders:orders.length,lowProducts:low.slice(0,8)});}));
r.get('/dashboard/charts',wrap(async(req,res)=>{
  const db=await readDb(),orders=visibleOrders(db,req.user),isCoordinator=req.user.role==='coordinator';
  const requestedDays=Number(req.query.days),days=[7,30,90].includes(requestedDays)?requestedDays:30;
  const today=new Date();today.setUTCHours(0,0,0,0);
  const dates=Array.from({length:days},(_,i)=>{const day=new Date(today);day.setUTCDate(day.getUTCDate()-(days-1)+i);return day.toISOString().slice(0,10);});
  const totals=new Map(dates.map(date=>[date,{income:0,outcome:0}]));
  if(!isCoordinator)for(const movement of db.inventoryMovements){const date=movement.createdAt?.slice(0,10),row=totals.get(date);if(row&&(movement.type==='income'||movement.type==='outcome'))row[movement.type]+=Number(movement.quantity)||0;}
  const dailyStats=dates.map(date=>({date,orders:isCoordinator?orders.filter(o=>o.createdAt?.slice(0,10)===date).length:0,...totals.get(date)}));
  const itemScope=db.orderItems.filter(item=>orders.some(order=>order.id===item.orderId));
  const products=(isCoordinator?db.products.filter(product=>itemScope.some(item=>item.productId===product.id)):db.products).map(product=>({name:product.name,quantity:itemScope.filter(item=>item.productId===product.id).reduce((sum,item)=>sum+item.requestedQuantity,0)})).sort((a,b)=>b.quantity-a.quantity).slice(0,7);
  ok(res,{dailyStats,statuses:Object.entries(ordersStatus(db,req.user)).map(([name,value])=>({name,value})),topProducts:products,movements:dailyStats.slice(-14)});
}));
function ordersStatus(db,user){const count={};for(const o of visibleOrders(db,user))count[o.status]=(count[o.status]||0)+1;return count;}
r.get('/dashboard/alerts',wrap(async(req,res)=>{const db=await readDb();ok(res,{lowStock:db.products.filter(p=>p.quantity-p.reservedQuantity<=p.minimumQuantity),lateOrders:visibleOrders(db,req.user).filter(o=>!['delivered','cancelled'].includes(o.status)&&o.requiredDate<new Date().toISOString().slice(0,10))});}));

r.get('/users',allow(...roles.admin),wrap(async(req,res)=>{const db=await readDb(),out=filterList(db.users.map(userSafe),req);ok(res,out.rows,'Foydalanuvchilar',out.meta);}));
r.get('/users/:id',allow(...roles.admin),wrap(async(req,res)=>{const db=await readDb();ok(res,userSafe(byId(db.users,req.params.id,'Foydalanuvchi')));}));
r.post('/users',allow(...roles.admin),wrap(async(req,res)=>{const input=z.object({username:z.string().min(3).max(40),password:z.string().min(8),name:z.string().min(2),role:z.enum(['admin','coordinator','warehouse','supply','logistics'])}).parse(req.body);const user=await mutateDb(async db=>{if(db.users.some(u=>u.username===input.username))throw new AppError('Login band',409);const u={id:uuid(),...input,passwordHash:await bcrypt.hash(input.password,10),active:true,createdAt:new Date().toISOString()};delete u.password;db.users.push(u);audit(db,req,'user.created','user',u.id,null,userSafe(u));return userSafe(u);});ok(res,user,'Foydalanuvchi yaratildi');}));
r.patch('/users/:id',allow(...roles.admin),wrap(async(req,res)=>{const data=await mutateDb(db=>{const u=byId(db.users,req.params.id,'Foydalanuvchi');const old=userSafe(u);for(const k of ['name','role','active','telegramId'])if(req.body[k]!==undefined)u[k]=req.body[k];if(req.body.password)u.passwordHash=bcrypt.hashSync(String(req.body.password),10);audit(db,req,'user.updated','user',u.id,old,userSafe(u));return userSafe(u);});ok(res,data);}));
r.patch('/users/:id/status',allow(...roles.admin),wrap(async(req,res)=>{req.body.active=Boolean(req.body.active);req.params.id=req.params.id;const d=await mutateDb(db=>{const u=byId(db.users,req.params.id);const old=u.active;u.active=req.body.active;audit(db,req,'user.status','user',u.id,old,u.active);return userSafe(u);});ok(res,d);}));

r.get('/products',wrap(async(req,res)=>{const db=await readDb();let rows=db.products.map(p=>({...p,availableQuantity:p.quantity-p.reservedQuantity,category:db.categories.find(c=>c.id===p.categoryId),warehouse:db.warehouses.find(w=>w.id===p.warehouseId)}));const out=filterList(rows,req);if(req.query.format==='csv'){res.type('text/csv').send(['SKU,Nomi,Miqdor,Rezerv,Mavjud,Minimum',...rows.map(p=>[p.sku,`"${p.name.replaceAll('"','""')}"`,p.quantity,p.reservedQuantity,p.availableQuantity,p.minimumQuantity].join(','))].join('\n'));return;}ok(res,out.rows,'Mahsulotlar',out.meta);}));
r.get('/products/:id',wrap(async(req,res)=>{const db=await readDb();ok(res,byId(db.products,req.params.id,'Mahsulot'));}));
r.post('/products',allow(...roles.admin,...roles.warehouse),wrap(async(req,res)=>{const data=z.object({name:z.string().min(2),sku:z.string().min(2),categoryId:z.string(),unit:z.string(),quantity:z.coerce.number().nonnegative().default(0),minimumQuantity:z.coerce.number().nonnegative().default(0),warehouseId:z.string(),weight:z.coerce.number().nonnegative().default(0),volume:z.coerce.number().nonnegative().default(0),location:z.string().optional(),price:z.coerce.number().nonnegative().default(0)}).parse(req.body);const p=await mutateDb(db=>{byId(db.categories,data.categoryId,'Kategoriya');byId(db.warehouses,data.warehouseId,'Ombor');if(db.products.some(x=>x.sku===data.sku))throw new AppError('SKU avval ishlatilgan',409);const x={id:uuid(),...data,reservedQuantity:0,status:'active',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.products.push(x);audit(db,req,'product.created','product',x.id,null,x);return x;});ok(res,p,'Mahsulot yaratildi');}));
r.patch('/products/:id',allow(...roles.admin,...roles.warehouse),wrap(async(req,res)=>{const p=await mutateDb(db=>{const x=byId(db.products,req.params.id,'Mahsulot'),old={...x};for(const k of ['name','sku','categoryId','unit','minimumQuantity','warehouseId','weight','volume','location','price','status'])if(req.body[k]!==undefined)x[k]=req.body[k];x.updatedAt=new Date().toISOString();audit(db,req,'product.updated','product',x.id,old,x);return x;});ok(res,p);}));
r.delete('/products/:id',allow(...roles.admin),wrap(async(req,res)=>{await mutateDb(db=>{const p=byId(db.products,req.params.id,'Mahsulot');if(p.reservedQuantity)throw new AppError('Rezervlangan mahsulotni oʻchirib boʻlmaydi',409);db.products=db.products.filter(x=>x.id!==p.id);audit(db,req,'product.deleted','product',p.id,p,null);});ok(res,null,'Mahsulot oʻchirildi');}));

r.get('/orders',wrap(async(req,res)=>{const db=await readDb();const out=filterList(visibleOrders(db,req.user).map(o=>orderView(db,o)),req);ok(res,out.rows,'Zayavkalar',out.meta);}));
r.get('/orders/:id',wrap(async(req,res)=>{const db=await readDb(),o=getOrder(db,req.params.id);if(req.user.role==='coordinator'&&o.coordinatorId!==req.user.id)throw new AppError('Bu zayavkani koʻrish ruxsati yoʻq',403);ok(res,orderView(db,o));}));
r.post('/orders',allow(...roles.coord),wrap(async(req,res)=>{const input=z.object({objectId:z.string(),requiredDate:z.string(),priority:z.enum(['low','medium','high','urgent']).default('medium'),comment:z.string().max(2000).optional(),items:z.array(z.object({productId:z.string(),requestedQuantity:z.coerce.number().positive(),comment:z.string().optional()})).min(1)}).parse(req.body);if(new Set(input.items.map(x=>x.productId)).size!==input.items.length)throw new AppError('Bitta mahsulotni zayavkaga ikki marta qoʻshmang',400);const o=await mutateDb(db=>{byId(db.objects,input.objectId,'Obyekt');for(const i of input.items)byId(db.products,i.productId,'Mahsulot');const n=db.orders.length+1;const order={id:uuid(),orderNumber:`Z-${new Date().getFullYear()}-${String(n).padStart(4,'0')}`,objectId:input.objectId,coordinatorId:req.user.id,priority:input.priority,requiredDate:input.requiredDate,status:'new',comment:input.comment||'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.orders.unshift(order);input.items.forEach(i=>db.orderItems.push({id:uuid(),orderId:order.id,productId:i.productId,requestedQuantity:i.requestedQuantity,reservedQuantity:0,shortageQuantity:0,pickedQuantity:0,loadedQuantity:0,comment:i.comment||''}));audit(db,req,'order.created','order',order.id,null,order);notify(db,['warehouse'],'Yangi zayavka',`${order.orderNumber} ombor tekshiruvini kutmoqda.`,`/orders/${order.id}`);return orderView(db,order);});ok(res,o,'Zayavka yaratildi',{},201);}));
r.patch('/orders/:id',allow(...roles.coord),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(req.user.role==='coordinator'&&o.coordinatorId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);if(o.status!=='new')throw new AppError('Faqat yangi zayavkani tahrirlash mumkin',409);const old={...o};for(const k of ['objectId','requiredDate','priority','comment'])if(req.body[k]!==undefined)o[k]=req.body[k];audit(db,req,'order.updated','order',o.id,old,o);return orderView(db,o);});ok(res,out);}));
r.delete('/orders/:id',allow(...roles.coord),wrap(async(req,res)=>{const o=await mutateDb(db=>{const x=getOrder(db,req.params.id);if(req.user.role==='coordinator'&&x.coordinatorId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);if(x.status!=='new')throw new AppError('Boshlangan zayavkani bekor qiling',409);db.orders=db.orders.filter(y=>y.id!==x.id);db.orderItems=db.orderItems.filter(i=>i.orderId!==x.id);audit(db,req,'order.deleted','order',x.id,x,null);return x;});ok(res,o,'Zayavka oʻchirildi');}));
r.patch('/orders/:id/status',allow(...roles.ops),wrap(async(req,res)=>{const o=await mutateDb(db=>{const x=getOrder(db,req.params.id);const status=z.enum(['new','checking','shortage','sent_to_supply','supply_in_progress','ready_for_picking','picking','documents_ready','waiting_transport','ready_for_loading','loading','shipped','delivered','cancelled']).parse(req.body.status);changeStatus(db,req,x,status);return orderView(db,x);});ok(res,o);}));
r.post('/orders/:id/check-stock',allow(...roles.warehouse),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(o.status==='new')changeStatus(db,req,o,'checking');if(!['checking','shortage','sent_to_supply','supply_in_progress'].includes(o.status))throw new AppError('Bu zayavkani qayta tekshirib boʻlmaydi',409);return {check:checkOrder(db,req,o),order:orderView(db,o)};});ok(res,out,'Ombor qoldigʻi tekshirildi');}));
r.post('/orders/:id/reserve',allow(...roles.warehouse),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(o.status==='new')changeStatus(db,req,o,'checking');return orderView(db,checkOrder(db,req,o)&&o);});ok(res,out,'Mavjud mahsulotlar rezervlandi');}));
r.post('/orders/:id/release-reservation',allow(...roles.warehouse),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);for(const i of db.orderItems.filter(x=>x.orderId===o.id)){const p=byId(db.products,i.productId);p.reservedQuantity=Math.max(0,p.reservedQuantity-i.reservedQuantity);i.reservedQuantity=0;}db.reservations.filter(x=>x.orderId===o.id&&x.status==='active').forEach(x=>x.status='released');audit(db,req,'reservation.released','order',o.id);return orderView(db,o);});ok(res,out,'Rezervlar boʻshatildi');}));
r.post('/orders/:id/pick',allow(...roles.warehouse),wrap(async(req,res)=>{const input=z.object({items:z.array(z.object({itemId:z.string(),pickedQuantity:z.coerce.number().nonnegative()})).optional()}).parse(req.body);const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(o.status==='ready_for_picking')changeStatus(db,req,o,'picking');if(o.status!=='picking')throw new AppError('Zayavka yigʻishga tayyor emas',409);for(const row of input.items||[]){const it=db.orderItems.find(x=>x.id===row.itemId&&x.orderId===o.id);if(!it)throw new AppError('Mahsulot qatori topilmadi',404);const qty=Number(row.pickedQuantity);if(!Number.isFinite(qty)||qty<0||qty>it.reservedQuantity)throw new AppError('Yigʻilgan miqdor rezervdan oshmasin',400);it.pickedQuantity=qty;}const items=db.orderItems.filter(i=>i.orderId===o.id);if(items.every(i=>i.pickedQuantity>=i.requestedQuantity)){changeStatus(db,req,o,'documents_ready');createInvoiceAndTransport(db,req,o);changeStatus(db,req,o,'waiting_transport');notify(db,['logistics'],'Transport soʻrovi yaratildi',`${o.orderNumber} uchun mashina tayinlang.`,`/transport-requests`);}audit(db,req,'order.picked','order',o.id);return orderView(db,o);});ok(res,out,'Yigʻish maʼlumotlari saqlandi');}));
r.post('/orders/:id/load',allow(...roles.warehouse),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(o.status==='ready_for_loading')changeStatus(db,req,o,'loading');if(o.status!=='loading')throw new AppError('Zayavka yuklashga tayyor emas',409);for(const i of db.orderItems.filter(x=>x.orderId===o.id)){const qty=i.pickedQuantity;if(qty>i.reservedQuantity)throw new AppError('Yuk miqdori rezervdan oshdi',409);const p=byId(db.products,i.productId);p.quantity-=qty;p.reservedQuantity-=qty;i.loadedQuantity=qty;db.inventoryMovements.unshift({id:uuid(),productId:p.id,warehouseId:p.warehouseId,type:'outcome',quantity:qty,previousQuantity:p.quantity+qty,newQuantity:p.quantity,referenceType:'shipment',referenceId:o.id,userId:req.user.id,comment:`${o.orderNumber} boʻyicha yuklandi`,createdAt:new Date().toISOString()});}const transport=db.transportRequests.find(t=>t.orderId===o.id);if(transport){transport.status='loading';transport.loadingStartedAt=new Date().toISOString();}audit(db,req,'order.loaded','order',o.id);return orderView(db,o);});ok(res,out,'Mahsulotlar yuklandi');}));
r.post('/orders/:id/ship',allow(...roles.warehouse,...roles.logistics),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(o.status==='loading')changeStatus(db,req,o,'shipped');else if(o.status!=='shipped')throw new AppError('Avval yuklashni yakunlang',409);const transport=db.transportRequests.find(x=>x.orderId===o.id);if(transport){transport.status='departed';transport.departedAt=new Date().toISOString();}if(!db.shipments.some(s=>s.orderId===o.id)){const s={id:uuid(),shipmentNumber:`SH-${new Date().getFullYear()}-${String(db.shipments.length+1).padStart(4,'0')}`,orderId:o.id,status:'shipped',shippedAt:new Date().toISOString()};db.shipments.push(s);audit(db,req,'shipment.created','shipment',s.id);}notify(db,['coordinator','logistics'],'Zayavka joʻnatildi',`${o.orderNumber} obyektga yoʻl oldi.`,`/orders/${o.id}`);return orderView(db,o);});ok(res,out,'Zayavka joʻnatildi');}));
r.post('/orders/:id/deliver',allow(...roles.logistics),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);changeStatus(db,req,o,'delivered');const s=db.shipments.find(x=>x.orderId===o.id);if(s){s.status='delivered';s.deliveredAt=new Date().toISOString();}const t=db.transportRequests.find(x=>x.orderId===o.id);if(t)t.status='delivered';audit(db,req,'shipment.delivered','order',o.id);notify(db,['coordinator','warehouse'],'Yetkazib berildi',`${o.orderNumber} yopildi.`,`/orders/${o.id}`);return orderView(db,o);});ok(res,out,'Yetkazib berish tasdiqlandi');}));
r.post('/orders/:id/cancel',allow(...roles.admin,...roles.coord,...roles.warehouse),wrap(async(req,res)=>{const out=await mutateDb(db=>{const o=getOrder(db,req.params.id);if(req.user.role==='coordinator'&&o.coordinatorId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);if(['shipped','delivered'].includes(o.status))throw new AppError('Joʻnatilgan zayavkani bekor qilib boʻlmaydi',409);for(const i of db.orderItems.filter(x=>x.orderId===o.id)){const p=byId(db.products,i.productId);const unused=Math.max(0,i.reservedQuantity-i.loadedQuantity);p.reservedQuantity=Math.max(0,p.reservedQuantity-unused);i.reservedQuantity=0;}for(const x of db.reservations.filter(x=>x.orderId===o.id&&x.status==='active'))x.status='released';changeStatus(db,req,o,'cancelled');return orderView(db,o);});ok(res,out,'Zayavka bekor qilindi');}));

r.get('/inventory',wrap(async(req,res)=>{const db=await readDb(),rows=db.products.map(p=>({...p,availableQuantity:p.quantity-p.reservedQuantity,category:db.categories.find(c=>c.id===p.categoryId),warehouse:db.warehouses.find(w=>w.id===p.warehouseId)}));const out=filterList(rows,req);ok(res,out.rows,'Ombor qoldigʻi',out.meta);}));
r.get('/inventory/movements',wrap(async(req,res)=>{const db=await readDb(),out=filterList(db.inventoryMovements.map(m=>({...m,product:db.products.find(p=>p.id===m.productId)})),req);ok(res,out.rows,'Ombor harakatlari',out.meta);}));
async function movement(req,res,type){const input=z.object({productId:z.string(),quantity:z.coerce.number().positive(),comment:z.string().optional(),warehouseId:z.string().optional()}).parse(req.body);const p=await mutateDb(db=>{const x=byId(db.products,input.productId,'Mahsulot'),prev=x.quantity;if(type==='outcome'&&input.quantity>x.quantity-x.reservedQuantity)throw new AppError('Erkin qoldiq yetarli emas',409);x.quantity+=type==='income'?input.quantity:-input.quantity;x.updatedAt=new Date().toISOString();const m={id:uuid(),productId:x.id,warehouseId:input.warehouseId||x.warehouseId,type,quantity:input.quantity,previousQuantity:prev,newQuantity:x.quantity,referenceType:'manual',referenceId:null,userId:req.user.id,comment:input.comment||'',createdAt:new Date().toISOString()};db.inventoryMovements.unshift(m);audit(db,req,`inventory.${type}`,'product',x.id,prev,x.quantity);return m;});ok(res,p,'Ombor harakati yozildi');}
r.post('/inventory/income',allow(...roles.admin,...roles.warehouse,...roles.supply),wrap((req,res)=>movement(req,res,'income')));
r.post('/inventory/outcome',allow(...roles.admin,...roles.warehouse),wrap((req,res)=>movement(req,res,'outcome')));
r.post('/inventory/adjustment',allow(...roles.admin,...roles.warehouse),wrap(async(req,res)=>{const input=z.object({productId:z.string(),quantity:z.coerce.number(),comment:z.string().min(3)}).parse(req.body);const m=await mutateDb(db=>{const p=byId(db.products,input.productId),prev=p.quantity;if(input.quantity<p.reservedQuantity)throw new AppError('Miqdor aktiv rezervdan past boʻlmasin',409);p.quantity=input.quantity;const x={id:uuid(),productId:p.id,warehouseId:p.warehouseId,type:'adjustment',quantity:input.quantity-prev,previousQuantity:prev,newQuantity:p.quantity,userId:req.user.id,comment:input.comment,createdAt:new Date().toISOString()};db.inventoryMovements.unshift(x);audit(db,req,'inventory.adjustment','product',p.id,prev,p.quantity);return x;});ok(res,m,'Qoldiq tuzatildi');}));
r.post('/inventory/transfer',allow(...roles.admin,...roles.warehouse),wrap(async(req,res)=>{throw new AppError('Omborlararo balans MVPda bitta mahsulot qoldigʻi bilan yuritiladi; transfer uchun alohida warehouse stock modeli kerak',501);}));

r.get('/shortages',allow(...roles.admin,...roles.warehouse,...roles.supply),wrap(async(req,res)=>{const db=await readDb(),rows=db.shortages.map(s=>({...s,product:db.products.find(p=>p.id===s.productId),order:db.orders.find(o=>o.id===s.orderId)}));const out=filterList(rows,req);ok(res,out.rows,'Yetishmovchiliklar',out.meta);}));r.get('/shortages/:id',wrap(async(req,res)=>{const db=await readDb();ok(res,byId(db.shortages,req.params.id,'Yetishmovchilik'));}));
r.get('/supply-requests',allow(...roles.admin,...roles.supply,...roles.warehouse),wrap(async(req,res)=>{const db=await readDb(),out=filterList(db.supplyRequests.map(x=>({...x,product:db.products.find(p=>p.id===x.productId),order:db.orders.find(o=>o.id===x.orderId),supplier:db.suppliers.find(s=>s.id===x.supplierId)})),req);ok(res,out.rows,'Taʼminot soʻrovlari',out.meta);}));
r.get('/supply-requests/:id',allow(...roles.admin,...roles.supply,...roles.warehouse),wrap(async(req,res)=>{const db=await readDb();ok(res,byId(db.supplyRequests,req.params.id,'Taʼminot soʻrovi'));}));
r.post('/supply-requests',allow(...roles.admin,...roles.supply),wrap(async(req,res)=>{const input=z.object({orderId:z.string(),productId:z.string(),requestedQuantity:z.coerce.number().positive(),supplierId:z.string().optional(),expectedDate:z.string().optional(),purchasePrice:z.coerce.number().nonnegative().optional(),comment:z.string().optional()}).parse(req.body);const s=await mutateDb(db=>{const o=getOrder(db,input.orderId);const x={id:uuid(),requestNumber:`SR-${new Date().getFullYear()}-${String(db.supplyRequests.length+1).padStart(4,'0')}`,...input,availableQuantity:0,shortageQuantity:input.requestedQuantity,assignedTo:req.user.id,status:'new',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.supplyRequests.push(x);audit(db,req,'supply.created','supplyRequest',x.id);notify(db,['warehouse','coordinator'],'Taʼminot soʻrovi yaratildi',x.requestNumber,`/supply-requests`);return x;});ok(res,s,'Taʼminot soʻrovi yaratildi');}));
r.patch('/supply-requests/:id',allow(...roles.admin,...roles.supply),wrap(async(req,res)=>{const s=await mutateDb(db=>{const x=byId(db.supplyRequests,req.params.id,'Taʼminot soʻrovi');const status=req.body.status;const supplyTransitions={new:['accepted','cancelled'],accepted:['ordered','cancelled'],ordered:['in_transit','cancelled'],in_transit:['cancelled'],received:[],cancelled:[]};if(status&&!supplyTransitions[x.status]?.includes(status))throw new AppError('Taʼminot status oʻtishi yaroqsiz',409);for(const k of ['supplierId','expectedDate','purchasePrice','comment'])if(req.body[k]!==undefined)x[k]=req.body[k];if(status==='ordered'&&(!x.supplierId||!x.expectedDate))throw new AppError('Buyurtma qilishdan oldin yetkazib beruvchi va kelish sanasini kiriting');if(status)x.status=status;x.updatedAt=new Date().toISOString();audit(db,req,'supply.updated','supplyRequest',x.id,null,x);return x;});ok(res,s);}));
r.post('/supply-requests/:id/receive',allow(...roles.admin,...roles.supply,...roles.warehouse),wrap(async(req,res)=>{const result=await mutateDb(db=>{const s=byId(db.supplyRequests,req.params.id,'Taʼminot soʻrovi');if(s.status!=='in_transit')throw new AppError('Mahsulotni qabul qilishdan oldin soʻrov yoʻlda boʻlishi kerak',409);const qty=Number(req.body.quantity||s.shortageQuantity);if(!Number.isFinite(qty)||qty<=0)throw new AppError('Miqdor musbat boʻlsin');if(qty>s.shortageQuantity)throw new AppError('Qabul qilinayotgan miqdor taʼminot soʻrovi miqdoridan oshmasin',409);const p=byId(db.products,s.productId),prev=p.quantity;p.quantity+=qty;s.receivedDate=new Date().toISOString().slice(0,10);s.status='received';s.updatedAt=new Date().toISOString();db.inventoryMovements.unshift({id:uuid(),productId:p.id,warehouseId:p.warehouseId,type:'income',quantity:qty,previousQuantity:prev,newQuantity:p.quantity,referenceType:'supplyRequest',referenceId:s.id,userId:req.user.id,comment:s.requestNumber+' qabul qilindi',createdAt:new Date().toISOString()});const o=getOrder(db,s.orderId);const checked=checkOrder(db,req,o);audit(db,req,'supply.received','supplyRequest',s.id,prev,p.quantity);notify(db,['warehouse','coordinator'],'Mahsulot omborga keldi',`${p.name}: ${qty} ${p.unit}`,`/orders/${o.id}`);return {request:s,order:orderView(db,o),check:checked};});ok(res,result,'Mahsulot qabul qilindi');}));
r.post('/supply-requests/:id/cancel',allow(...roles.admin,...roles.supply),wrap(async(req,res)=>{const s=await mutateDb(db=>{const x=byId(db.supplyRequests,req.params.id);x.status='cancelled';x.updatedAt=new Date().toISOString();audit(db,req,'supply.cancelled','supplyRequest',x.id);return x;});ok(res,s,'Soʻrov bekor qilindi');}));

r.get('/invoices',allow(...roles.admin,...roles.warehouse,...roles.coordinator,...roles.logistics),wrap(async(req,res)=>{const db=await readDb(),rows=(req.user.role==='coordinator'?db.invoices.filter(i=>db.orders.find(o=>o.id===i.orderId)?.coordinatorId===req.user.id):db.invoices).map(i=>({...i,order:db.orders.find(o=>o.id===i.orderId),object:db.objects.find(x=>x.id===db.orders.find(o=>o.id===i.orderId)?.objectId)}));const out=filterList(rows,req);ok(res,out.rows,'Nakladnoylar',out.meta);}));r.get('/invoices/:id',allow(...roles.admin,...roles.warehouse,...roles.coordinator,...roles.logistics),wrap(async(req,res)=>{const db=await readDb(),inv=byId(db.invoices,req.params.id,'Nakladnoy'),order=getOrder(db,inv.orderId);if(req.user.role==='coordinator'&&order.coordinatorId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);ok(res,inv);}));
r.post('/invoices',allow(...roles.admin,...roles.warehouse),wrap(async(req,res)=>{const x=await mutateDb(db=>{const o=getOrder(db,req.body.orderId);const inv=createInvoiceAndTransport(db,req,o);audit(db,req,'invoice.created','invoice',inv.id);return inv;});ok(res,x,'Nakladnoy tayyor');}));
r.get('/invoices/:id/pdf',allow(...roles.ops),wrap(async(req,res)=>{const db=await readDb(),inv=byId(db.invoices,req.params.id,'Nakladnoy'),o=getOrder(db,inv.orderId),object=db.objects.find(x=>x.id===o.objectId);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename=${inv.invoiceNumber}.pdf`);const doc=new PDFDocument({margin:48});doc.pipe(res);doc.fontSize(20).text('SMART WAREHOUSE CONTROL',{align:'center'}).moveDown(.3).fontSize(15).text(`YUK XATI  ${inv.invoiceNumber}`,{align:'center'}).moveDown();doc.fontSize(10).text(`Zayavka: ${o.orderNumber}     Sana: ${new Date(inv.createdAt).toLocaleDateString('uz-UZ')}`).text(`Obyekt: ${object?.name||''}`).text(`Manzil: ${object?.address||''}`).moveDown().fontSize(11).text('Mahsulot                              SKU                         Miqdor');doc.moveTo(48,doc.y+4).lineTo(550,doc.y+4).stroke();doc.moveDown(.5);for(const row of inv.items||[]){const p=db.products.find(x=>x.id===row.productId);doc.fontSize(9).text(`${p?.name||row.productId}     ${p?.sku||''}     ${row.pickedQuantity||row.requestedQuantity} ${p?.unit||''}`);}doc.moveDown().fontSize(10).text(`Jami ogʻirlik: ${inv.weight||0} kg     Hajm: ${inv.volume||0} m³`).moveDown(3).text('Ombor masʼuli: ____________________       Qabul qiluvchi: ____________________');doc.end();}));

r.get('/transport-requests',allow(...roles.admin,...roles.logistics,...roles.warehouse),wrap(async(req,res)=>{const db=await readDb(),out=filterList(db.transportRequests.map(t=>({...t,order:db.orders.find(o=>o.id===t.orderId),vehicle:db.vehicles.find(v=>v.id===t.vehicleId),driver:db.drivers.find(d=>d.id===t.driverId)})),req);ok(res,out.rows,'Transport soʻrovlari',out.meta);}));r.get('/transport-requests/:id',allow(...roles.admin,...roles.logistics,...roles.warehouse),wrap(async(req,res)=>{const db=await readDb();ok(res,byId(db.transportRequests,req.params.id,'Transport soʻrovi'));}));
r.post('/transport-requests',allow(...roles.admin,...roles.logistics),wrap(async(req,res)=>{const t=await mutateDb(db=>{const o=getOrder(db,req.body.orderId);return createInvoiceAndTransport(db,req,o)&&db.transportRequests.find(x=>x.orderId===o.id);});ok(res,t,'Transport soʻrovi tayyor');}));
r.patch('/transport-requests/:id',allow(...roles.admin,...roles.logistics),wrap(async(req,res)=>{const t=await mutateDb(db=>{const x=byId(db.transportRequests,req.params.id);if(req.body.status)throw new AppError('Transport statusini /confirm workflow orqali oʻzgartiring',409);for(const k of ['loadingAt','comment'])if(req.body[k]!==undefined)x[k]=req.body[k];return x;});ok(res,t);}));
r.post('/transport-requests/:id/assign',allow(...roles.admin,...roles.logistics),wrap(async(req,res)=>{const t=await mutateDb(db=>{const x=byId(db.transportRequests,req.params.id),v=byId(db.vehicles,req.body.vehicleId,'Mashina'),d=byId(db.drivers,req.body.driverId,'Haydovchi');if(x.weight>v.capacityWeight||x.volume>v.capacityVolume)throw new AppError(`Mashina sigʻimi yetmaydi (yuk ${x.weight}kg/${x.volume}m³, sigʻim ${v.capacityWeight}kg/${v.capacityVolume}m³)`,409);if(v.status!=='available'||d.status!=='available')throw new AppError('Mashina yoki haydovchi band',409);x.vehicleId=v.id;x.driverId=d.id;x.loadingAt=req.body.loadingAt||null;x.status='assigned';v.status='assigned';d.status='assigned';const o=getOrder(db,x.orderId);if(o.status==='waiting_transport')changeStatus(db,req,o,'ready_for_loading');audit(db,req,'transport.assigned','transportRequest',x.id,null,{vehicleId:v.id,driverId:d.id});notify(db,['warehouse','coordinator'],'Transport biriktirildi',`${o.orderNumber}: ${v.name}, ${d.name}`,`/transport-requests`);return x;});ok(res,t,'Transport biriktirildi');}));
r.post('/transport-requests/:id/confirm',allow(...roles.admin,...roles.logistics),wrap(async(req,res)=>{const t=await mutateDb(db=>{const x=byId(db.transportRequests,req.params.id);if(!x.vehicleId)throw new AppError('Avval mashina biriktiring',409);const transportTransitions={requested:['cancelled'],assigned:['arrived_for_loading','cancelled'],arrived_for_loading:['loading','cancelled'],loading:['cancelled'],departed:[],delivered:[],cancelled:[]};const next=req.body.status||x.status;if(next!==x.status&&!transportTransitions[x.status]?.includes(next))throw new AppError('Transport status oʻtishi yaroqsiz',409);x.status=next;if(x.status==='arrived_for_loading')x.arrivedAt=new Date().toISOString();if(x.status==='departed')x.departedAt=new Date().toISOString();audit(db,req,'transport.status','transportRequest',x.id,null,x.status);return x;});ok(res,t);}));

r.get('/shipments',allow(...roles.admin,...roles.logistics,...roles.warehouse,...roles.coordinator),wrap(async(req,res)=>{const db=await readDb(),rows=(req.user.role==='coordinator'?db.shipments.filter(s=>db.orders.find(o=>o.id===s.orderId)?.coordinatorId===req.user.id):db.shipments).map(s=>({...s,order:db.orders.find(o=>o.id===s.orderId),object:db.objects.find(x=>x.id===db.orders.find(o=>o.id===s.orderId)?.objectId)}));const out=filterList(rows,req);ok(res,out.rows,'Joʻnatmalar',out.meta);}));r.get('/shipments/:id',allow(...roles.admin,...roles.logistics,...roles.warehouse,...roles.coordinator),wrap(async(req,res)=>{const db=await readDb(),s=byId(db.shipments,req.params.id,'Joʻnatma'),o=getOrder(db,s.orderId);if(req.user.role==='coordinator'&&o.coordinatorId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);ok(res,s);}));r.post('/shipments',allow(...roles.admin,...roles.logistics),wrap(async(req,res)=>{throw new AppError('Joʻnatma yuklash/joʻnatish workflow orqali yaratiladi',409);}));r.patch('/shipments/:id/status',allow(...roles.admin,...roles.logistics),wrap(async(req,res)=>{const s=await mutateDb(db=>{const x=byId(db.shipments,req.params.id);const o=getOrder(db,x.orderId);if(req.body.status==='delivered'&&o.status==='shipped'){changeStatus(db,req,o,'delivered');x.status='delivered';x.deliveredAt=new Date().toISOString();}else throw new AppError('Notoʻgʻri joʻnatma statusi',409);audit(db,req,'shipment.delivered','shipment',x.id);return x;});ok(res,s);}));

r.get('/notifications',wrap(async(req,res)=>{const db=await readDb(),rows=db.notifications.filter(n=>n.userId===req.user.id);const out=filterList(rows,req);ok(res,out.rows,'Bildirishnomalar',out.meta);}));r.patch('/notifications/:id/read',wrap(async(req,res)=>{const x=await mutateDb(db=>{const n=byId(db.notifications,req.params.id,'Bildirishnoma');if(n.userId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);n.readAt=new Date().toISOString();return n;});ok(res,x);}));r.patch('/notifications/read-all',wrap(async(req,res)=>{const count=await mutateDb(db=>{let n=0;for(const x of db.notifications.filter(x=>x.userId===req.user.id&&!x.readAt)){x.readAt=new Date().toISOString();n++;}return n;});ok(res,{updated:count},'Bildirishnomalar oʻqildi');}));
r.get('/audit-logs',allow(...roles.admin),wrap(async(req,res)=>{const db=await readDb(),out=filterList(db.auditLogs,req);ok(res,out.rows,'Audit jurnali',out.meta);}));
r.get('/ai/status',wrap(async(req,res)=>ok(res,{mode:['openai','gemini'].includes(config.aiProvider)&&config.aiApiKey&&config.aiModel?config.aiProvider:'mock',readOnly:true})));r.get('/ai/conversations',wrap(async(req,res)=>{const db=await readDb();ok(res,db.aiConversations.filter(c=>c.userId===req.user.id));}));r.get('/ai/conversations/:id',wrap(async(req,res)=>{const db=await readDb(),c=byId(db.aiConversations,req.params.id,'AI suhbat');if(c.userId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);ok(res,c);}));r.delete('/ai/conversations/:id',wrap(async(req,res)=>{await mutateDb(db=>{const c=byId(db.aiConversations,req.params.id);if(c.userId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);db.aiConversations=db.aiConversations.filter(x=>x.id!==c.id);});ok(res,null,'Suhbat oʻchirildi');}));r.post('/ai/chat',wrap(async(req,res)=>{const prompt=z.string().min(2).max(1000).parse(req.body.message);ok(res,await answerFor(req.user,prompt),'AI tahlili tayyor');}));r.post('/ai/daily-report',wrap(async(req,res)=>ok(res,await answerFor(req.user,'Bugungi rahbar hisobotini tayyorla'))));r.post('/ai/weekly-report',wrap(async(req,res)=>ok(res,await answerFor(req.user,'Haftalik hisobot va kechikish xavflarini koʻrsat'))));r.post('/ai/analyze-risks',wrap(async(req,res)=>ok(res,await answerFor(req.user,'Qaysi zayavkalarda kechikish xavfi bor?'))));r.post('/ai/analyze-order/:id',wrap(async(req,res)=>{const db=await readDb(),o=getOrder(db,req.params.id);if(req.user.role==='coordinator'&&o.coordinatorId!==req.user.id)throw new AppError('Ruxsat yoʻq',403);ok(res,await answerFor(req.user,`${o.orderNumber} zayavkasini tahlil qil`));}));

r.get('/categories',wrap(async(req,res)=>{const db=await readDb();ok(res,db.categories);}));r.post('/categories',allow(...roles.admin),wrap(async(req,res)=>{const x=await mutateDb(db=>{const c={id:uuid(),name:z.string().min(2).parse(req.body.name),description:req.body.description||''};db.categories.push(c);audit(db,req,'category.created','category',c.id);return c;});ok(res,x);}));
r.get('/warehouses',wrap(async(req,res)=>{ok(res,(await readDb()).warehouses);}));r.get('/objects',wrap(async(req,res)=>{ok(res,(await readDb()).objects);}));r.post('/objects',allow(...roles.admin,...roles.coord),wrap(async(req,res)=>{const x=await mutateDb(db=>{const o={id:uuid(),name:z.string().min(2).parse(req.body.name),address:req.body.address||'',contactName:req.body.contactName||'',phone:req.body.phone||'',active:true};db.objects.push(o);audit(db,req,'object.created','object',o.id);return o;});ok(res,x);}));
r.get('/vehicles',allow(...roles.admin,...roles.logistics,...roles.warehouse),wrap(async(req,res)=>ok(res,(await readDb()).vehicles)));r.get('/drivers',allow(...roles.admin,...roles.logistics,...roles.warehouse),wrap(async(req,res)=>ok(res,(await readDb()).drivers)));r.get('/suppliers',allow(...roles.admin,...roles.supply,...roles.warehouse),wrap(async(req,res)=>ok(res,(await readDb()).suppliers)));
r.get('/profile',wrap(async(req,res)=>ok(res,userSafe(req.user))));r.patch('/profile',wrap(async(req,res)=>{const u=await mutateDb(db=>{const x=byId(db.users,req.user.id);if(req.body.name)x.name=z.string().min(2).parse(req.body.name);if(req.body.password)x.passwordHash=bcrypt.hashSync(z.string().min(8).parse(req.body.password),10);audit(db,req,'profile.updated','user',x.id);return userSafe(x);});ok(res,u);}));
r.get('/settings',allow(...roles.admin),wrap(async(req,res)=>ok(res,(await readDb()).settings.filter(s=>s.key!=='telegramLoginCodes'))));r.patch('/settings',allow(...roles.admin),wrap(async(req,res)=>{const s=await mutateDb(db=>{const key=z.string().min(1).parse(req.body.key),row=db.settings.find(x=>x.key===key);if(row)row.value=req.body.value;else db.settings.push({key,value:req.body.value});audit(db,req,'settings.updated','setting',key);return {key,value:req.body.value};});ok(res,s);}));
r.post('/telegram/link-code',wrap(async(req,res)=>{const code=String(randomInt(100000,1000000));await mutateDb(db=>{const rows=db.settings.find(s=>s.key==='telegramLoginCodes')?.value||[];const next=db.settings.find(s=>s.key==='telegramLoginCodes');if(next)next.value=rows.filter(x=>x.userId!==req.user.id).concat({userId:req.user.id,code,expiresAt:Date.now()+600000});});ok(res,{code,expiresInSeconds:600},'Telegram ulash kodi');}));
r.post('/admin/backup',allow(...roles.admin),wrap(async(req,res)=>ok(res,{file:await backupDb()},'Backup yaratildi')));
export default r;
