import test from 'node:test';
import assert from 'node:assert/strict';
import { changeStatus,checkOrder } from '../src/services/workflow.js';
const req=(role='warehouse')=>({user:{id:`user_${role}`,role},ip:'127.0.0.1',get:()=> 'test'});
function fixture(){return {orders:[{id:'o1',orderNumber:'Z-2026-9001',status:'checking',updatedAt:new Date().toISOString()}],orderItems:[{id:'i1',orderId:'o1',productId:'p1',requestedQuantity:8,reservedQuantity:0,shortageQuantity:0,pickedQuantity:0}],products:[{id:'p1',name:'Sement',quantity:10,reservedQuantity:2,minimumQuantity:1,unit:'qop',warehouseId:'w1'}],reservations:[],shortages:[],supplyRequests:[],auditLogs:[],notifications:[],users:[{id:'s1',role:'supply',active:true},{id:'w1',role:'warehouse',active:true}]};}
test('stock check reserves only the available amount and keeps physical quantity',()=>{const db=fixture(),order=db.orders[0];const result=checkOrder(db,req(),order);assert.equal(result.missing,0);assert.equal(db.products[0].quantity,10);assert.equal(db.products[0].reservedQuantity,10);assert.equal(db.orderItems[0].reservedQuantity,8);assert.equal(order.status,'ready_for_picking');});
test('shortage creates a supply request and never over-reserves',()=>{const db=fixture(),order=db.orders[0];db.products[0].quantity=6;const result=checkOrder(db,req(),order);assert.equal(result.missing,1);assert.equal(db.products[0].reservedQuantity,6);assert.equal(db.orderItems[0].shortageQuantity,4);assert.equal(db.supplyRequests.length,1);assert.equal(order.status,'supply_in_progress');});
test('after receipt a recheck moves the order to picking-ready',()=>{const db=fixture(),order=db.orders[0];db.products[0].quantity=6;checkOrder(db,req(),order);db.products[0].quantity+=4;const checked=checkOrder(db,req('supply'),order);assert.equal(checked.missing,0);assert.equal(db.products[0].reservedQuantity,10);assert.equal(order.status,'ready_for_picking');assert.equal(db.shortages[0].status,'resolved');});
test('arbitrary transitions and wrong-role transitions are rejected',()=>{const db=fixture(),order=db.orders[0];assert.throws(()=>changeStatus(db,req(),order,'delivered'),/oʻtish mumkin emas/);assert.throws(()=>changeStatus(db,{...req('coordinator')},order,'shortage'),/ruxsat yoʻq/);});
test('reservation is idempotent on repeated stock checks',()=>{const db=fixture(),order=db.orders[0];checkOrder(db,req(),order);const count=db.reservations.length;checkOrder(db,req(),order);assert.equal(db.reservations.length,count);assert.equal(db.products[0].reservedQuantity,10);});
