import { readDb, mutateDb } from '../repositories/jsonRepository.js';
import { v4 as uuid } from 'uuid';
import { enrichWithProvider } from './provider.js';
const scrub = u => ({id:u.id,name:u.name,role:u.role,telegramId:u.telegramId||null});
export async function answerFor(user, prompt) {
 const db=await readDb(); let orders=db.orders; if(user.role==='coordinator') orders=orders.filter(o=>o.coordinatorId===user.id);
 const visibleProductIds=user.role==='coordinator'?new Set(db.orderItems.filter(i=>orders.some(o=>o.id===i.orderId)).map(i=>i.productId)):null;
 const scopedProducts=visibleProductIds?db.products.filter(p=>visibleProductIds.has(p.id)):db.products;
 const low=scopedProducts.filter(p=>p.quantity-p.reservedQuantity<=p.minimumQuantity); const mine=orders.filter(o=>o.status!=='delivered'&&o.status!=='cancelled');const late=mine.filter(o=>o.requiredDate&&new Date(o.requiredDate)<new Date()); const shipped=db.shipments.filter(s=>s.status==='shipped'&&orders.some(o=>o.id===s.orderId)).length;
 const q=prompt.toLowerCase(); let summary,metrics=[],problems=[],recommendation,links=[];
 const requestedOrder=prompt.match(/Z-\d{4}-\d{4}/i)?.[0];
 if(requestedOrder){const order=orders.find(o=>o.orderNumber.toLowerCase()===requestedOrder.toLowerCase());if(!order){summary=`${requestedOrder} bo‘yicha sizga ko‘rinadigan yozuv topilmadi.`;recommendation='Zayavka raqamini tekshiring yoki administratorga murojaat qiling.';}else{const items=db.orderItems.filter(i=>i.orderId===order.id).map(i=>({...i,product:db.products.find(p=>p.id===i.productId)}));summary=`${order.orderNumber} — ${order.status}. Yetkazish muddati ${order.requiredDate}; ${items.length} ta mahsulot qatori bor.`;metrics=items.map(i=>({label:i.product?.name||'Mahsulot',value:`${i.reservedQuantity||0}/${i.requestedQuantity} rezerv`}));problems=items.filter(i=>i.shortageQuantity>0).map(i=>`${i.product?.name}: ${i.shortageQuantity} yetishmaydi`);recommendation=problems.length?'Taʼminot qabul qilingach zayavkani qayta tekshiring.':'Keyingi status uchun masʼul bo‘lim amalini kuting.';links=[{label:order.orderNumber,href:`/orders/${order.id}`}];}}
 else if(q.includes('kam')||q.includes('qoldiq')||q.includes('stock')){summary=`${low.length} ta ko‘rinadigan mahsulot minimal qoldiq chegarasida yoki undan past.`;metrics=low.slice(0,8).map(p=>({label:p.name,value:`${p.quantity-p.reservedQuantity} ${p.unit}`}));problems=low.map(p=>`${p.name}: erkin qoldiq ${p.quantity-p.reservedQuantity}, minimum ${p.minimumQuantity}`);recommendation='Yetkazib berish muddatini hisobga olib xarid soʻrovini rejalashtiring.';}
 else if(!requestedOrder&&(q.includes('kechik')||q.includes('risk'))){summary=`${late.length} ta faol zayavka muddati oʻtgan; faol zayavkalar ${mine.length} ta.`;metrics=[{label:'Muddati oʻtgan',value:late.length},{label:'Faol',value:mine.length}];problems=late.map(o=>`${o.orderNumber} — ${o.requiredDate}`);recommendation='Avval muddati oʻtgan va transport kutayotgan buyurtmalarni ko‘rib chiqing.';}
 else if(!requestedOrder&&(q.includes('transport')||q.includes('mashina'))){const waiting=orders.filter(o=>['waiting_transport','documents_ready'].includes(o.status));summary=`${waiting.length} ta zayavka transport bosqichiga kelgan.`;metrics=waiting.slice(0,6).map(o=>({label:o.orderNumber,value:o.status}));problems=[];recommendation='Yuk hajmi va ogʻirligini transport soʻrovlarida solishtiring.';}
 else if(!requestedOrder&&(q.includes('hisobot')||q.includes('bugun')||q.includes('kunlik'))){summary=user.role==='coordinator'?`Sizga tegishli ${orders.length} ta zayavka, shundan ${mine.length} tasi faol va ${late.length} tasi muddati o‘tgan.`:`Omborda ${db.products.reduce((s,p)=>s+p.quantity,0).toLocaleString('uz-UZ')} birlik bor. ${orders.length} ta zayavka, ${low.length} ta past qoldiq, ${shipped} ta joʻnatilgan yuk.`;metrics=user.role==='coordinator'?[{label:'Zayavkalarim',value:orders.length},{label:'Faol',value:mine.length},{label:'Muddati o‘tgan',value:late.length}]:[{label:'Mahsulot SKU',value:db.products.length},{label:'Birlik',value:db.products.reduce((s,p)=>s+p.quantity,0)},{label:'Faol zayavka',value:mine.length},{label:'Past qoldiq',value:low.length}];problems=late.map(o=>`${o.orderNumber} kechikish xavfida`);recommendation='Yetkazish sanasi yaqin buyurtmalarni va past qoldiqlarni rejalashtiring.';}
 else if(!requestedOrder){summary=`Maʼlumot bazasida siz ko‘ra oladigan ${orders.length} ta zayavka va ${scopedProducts.length} ta mahsulot bor.`;metrics=[{label:'Zayavkalar',value:orders.length},{label:'Ko‘rinadigan SKU',value:scopedProducts.length},{label:'Yangi taʼminot soʻrovi',value:user.role==='coordinator'?'cheklangan':db.supplyRequests.filter(s=>s.status==='new').length}];problems=[];recommendation='Savolni ombor qoldigʻi, kechikish, transport yoki kunlik hisobot bo‘yicha aniqlashtiring.';}
 const facts={summary,metrics,problems,recommendation};const context={orders:orders.slice(0,80).map(o=>({number:o.orderNumber,status:o.status,requiredDate:o.requiredDate})),lowStock:low.slice(0,80).map(p=>({name:p.name,available:p.quantity-p.reservedQuantity,minimum:p.minimumQuantity})),visibleProductCount:scopedProducts.length};const enhanced=await enrichWithProvider({question:prompt,facts,context});
 const result={...facts,analysis:enhanced.analysis,links:links.length?links:orders.slice(0,4).map(o=>({label:o.orderNumber,href:`/orders/${o.id}`})),asOf:new Date().toISOString(),mode:enhanced.mode};
 const safePrompt=prompt.replace(/\b(sk-[A-Za-z0-9_-]{12,}|Bearer\s+[A-Za-z0-9._-]{16,})\b/gi,'[REDACTED]').replace(/(password|parol|api[_ -]?key|token)\s*[:=]\s*\S+/gi,'$1=[REDACTED]').slice(0,1000);
 await mutateDb(d=>{d.aiConversations.push({id:uuid(),userId:user.id,prompt:safePrompt,answer:result,createdAt:new Date().toISOString()});}); return result;
}
