import bcrypt from 'bcryptjs';
import { v4 as uuid } from 'uuid';
const stamp=(days=0)=>new Date(Date.now()+days*86400000).toISOString();
export async function seedData(){
 const roles=[['admin','admin','Admin123!','Tizim administratori'],['coordinator','coordinator','Coordinator123!','Dilnoza Qodirova'],['warehouse','warehouse','Warehouse123!','Jasur Karimov'],['supply','supply','Supply123!','Madina Rasulova'],['logistics','logistics','Logistics123!','Akmal Sobirov']];
 const users=[];for(const [role,username,password,name] of roles)users.push({id:`user_${role}`,username,passwordHash:await bcrypt.hash(password,10),name,role,active:true,telegramId:null,createdAt:stamp(-90)});
 const categories=['Quruq qurilish','Elektr jihozlari','Santexnika','Xavfsizlik','Mahkamlash buyumlari'].map((name,i)=>({id:`cat_${i+1}`,name,description:`${name} mahsulotlari`}));
 const warehouses=[['wh_main','Toshkent markaziy ombori','Toshkent, Sergeli tumani'],['wh_north','Chirchiq hududiy ombori','Toshkent viloyati, Chirchiq'],['wh_south','Samarqand ombori','Samarqand shahri']].map(([id,name,address])=>({id,name,address,active:true}));
 const objects=[['obj_1','Yangi Toshkent turar joy majmuasi','Toshkent, Yangihayot tumani'],['obj_2','Samarqand logistika markazi','Samarqand, Kimyogarlar shaharchasi'],['obj_3','Chirchiq suv inshooti','Chirchiq, Istiqlol ko‘chasi'],['obj_4','Yunusobod biznes markazi','Toshkent, Yunusobod 17-mavze'],['obj_5','Navoiy ishlab chiqarish sexi','Navoiy shahri, Sanoat hududi']].map(([id,name,address],i)=>({id,name,address,contactName:['Otabek Hasanov','Shahnoza Eshonqulova','Ilhom Tursunov','Sardor Aliyev','Kamola Raximova'][i],phone:`+998 9${i+1} 234 56 7${i}`,active:true}));
 const names=['Portland sement M500','Armatura A500C Ø12','Gipsokarton 12.5 mm','Mis kabel VVGng 3×2.5','Polipropilen quvur 25 mm','Avtomat 16A C turi','Mineral paxta 50 mm','Suv krani 1/2 dyuym','Montaj ko‘pigi 750 ml','Anker bolt 10×100','Kafel yelimi 25 kg','LED panel 36W','PVC kanalizatsiya quvuri 110 mm','Himoya kaskasi EN397','Shisha tolali setka 160 g','RCD 40A 30mA','Shuruplar 4.2×75','Radiator bimetall 10 seksiyali','Bo‘yoq akril 15 kg','Yong‘in o‘chirgich 5 kg'];
 const units=['qop','metr','dona','metr','metr','dona','pachka','dona','dona','dona','qop','dona','metr','dona','rulon','dona','quti','dona','chelak','dona'];
 const products=names.map((name,i)=>({id:`prod_${String(i+1).padStart(2,'0')}`,name,sku:`SWC-${String(i+1).padStart(4,'0')}`,barcode:`478000000${String(i+1).padStart(4,'0')}`,categoryId:categories[i%5].id,unit:units[i],quantity:[420,1850,240,3600,980,140,76,215,88,620,195,110,740,90,44,68,320,55,112,38][i],reservedQuantity:[45,240,18,600,115,10,5,22,8,80,24,12,56,4,3,6,32,4,11,2][i],minimumQuantity:[100,500,80,700,180,40,25,40,20,150,50,30,150,25,12,18,80,15,30,10][i],weight:[50,0.888,8,0.15,0.2,0.12,5,0.2,0.5,0.3,25,1.1,1.5,0.35,4,0.25,1.2,16,15,7][i],volume:[0.04,0.00015,0.018,0.0001,0.0004,0.0002,0.035,0.0003,0.003,0.0003,0.02,0.004,0.009,0.003,0.01,0.001,0.002,0.03,0.02,0.01][i],warehouseId:warehouses[i%3].id,location:`${String.fromCharCode(65+i%5)}-${String(i%8+1).padStart(2,'0')}-${String(i%4+1).padStart(2,'0')}`,price:[68000,12500,92000,8600,14500,38000,74000,22000,42000,18000,51000,97000,32000,48000,155000,215000,35000,125000,134000,89000][i],status:'active',createdAt:stamp(-110),updatedAt:stamp(-1)}));
 const statuses=['new','checking','shortage','sent_to_supply','supply_in_progress','ready_for_picking','picking','documents_ready','waiting_transport','ready_for_loading','shipped','delivered'];
 const orders=statuses.map((status,i)=>({id:`order_${String(i+1).padStart(3,'0')}`,orderNumber:`Z-2026-${String(i+1).padStart(4,'0')}`,objectId:objects[i%5].id,coordinatorId:users[1].id,priority:['medium','high','urgent','low'][i%4],requiredDate:stamp(i<2?-1:i-4).slice(0,10),status,comment:['Qavatlar kesimida yetkazilsin','Yuk ertalab qabul qilinadi','Partiya sertifikati ilova qilinsin'][i%3],createdAt:stamp(-30+i*2),updatedAt:stamp(-Math.max(0,11-i))}));
 const orderItems=[];orders.forEach((o,i)=>{for(let j=0;j<2;j++){const p=products[(i*2+j)%products.length];const requestedQuantity=24+(i*9)+(j*12);const reservedQuantity=['new','checking'].includes(o.status)?0:['shortage','sent_to_supply','supply_in_progress'].includes(o.status)?Math.floor(requestedQuantity*.55):requestedQuantity;orderItems.push({id:`item_${i+1}_${j+1}`,orderId:o.id,productId:p.id,requestedQuantity,reservedQuantity,shortageQuantity:requestedQuantity-reservedQuantity,pickedQuantity:['picking','documents_ready','waiting_transport','ready_for_loading','shipped','delivered'].includes(o.status)?reservedQuantity:0,loadedQuantity:['shipped','delivered'].includes(o.status)?reservedQuantity:0});}});
 const suppliers=['Orient Qurilish Taʼminot','Baraka Elektro Savdo','Samarqand Sanoat Servis','Mega Plast Invest','Ishonch Qurilish Market'].map((name,i)=>({id:`supplier_${i+1}`,name,phone:`+998 90 321 4${i} 5${i}`,email:`sales${i+1}@example.uz`,active:true}));
 const vehicles=[['vehicle_1','Isuzu NPR','01 A 123 BC',3500,18],['vehicle_2','Hyundai Mighty','01 B 456 CD',5000,28],['vehicle_3','MAN TGL','30 C 789 EF',9000,42],['vehicle_4','Mercedes Sprinter','01 D 234 FG',1800,12]].map(([id,name,plate,capacityWeight,capacityVolume])=>({id,name,plate,capacityWeight,capacityVolume,status:'available'}));
 const drivers=[['driver_1','Farrux Ergashev'],['driver_2','Bekzod Mirzayev'],['driver_3','Ulug‘bek Soliyev'],['driver_4','Rustam Tohirov']].map(([id,name],i)=>({id,name,phone:`+998 90 555 12 0${i+1}`,licenseCategory:i===2?'CE':'C',status:'available'}));
 const shortages=orders.slice(2,7).map((o,i)=>({id:`shortage_${i+1}`,orderId:o.id,productId:products[i].id,requestedQuantity:120,availableQuantity:70,shortageQuantity:50,status:i<2?'open':'resolved',createdAt:o.createdAt}));
 const supplyRequests=shortages.slice(0,5).map((s,i)=>({id:`supply_${i+1}`,requestNumber:`SR-2026-${String(i+1).padStart(4,'0')}`,orderId:s.orderId,productId:s.productId,requestedQuantity:50,availableQuantity:70,shortageQuantity:50,supplierId:suppliers[i].id,purchasePrice:products[i].price,expectedDate:stamp(i+2).slice(0,10),receivedDate:i===4?stamp(-1).slice(0,10):null,assignedTo:users[3].id,status:['new','accepted','ordered','in_transit','received'][i],comment:'Qurilish jadvali bo‘yicha zarur',createdAt:stamp(-8+i),updatedAt:stamp(-1)}));
 const invoices=orders.slice(5,10).map((o,i)=>({id:`invoice_${i+1}`,invoiceNumber:`NK-2026-${String(i+1).padStart(4,'0')}`,orderId:o.id,items:orderItems.filter(x=>x.orderId===o.id),weight:320+i*85,volume:4.2+i*1.4,status:i<3?'ready':'issued',createdAt:stamp(-4+i)}));
 const transportRequests=orders.slice(4,10).map((o,i)=>({id:`transport_${i+1}`,requestNumber:`TR-2026-${String(i+1).padStart(4,'0')}`,orderId:o.id,objectId:o.objectId,weight:480+i*700,volume:6+i*3,quantity:80+i*20,recommendedVehicleType:i>3?'Yuk mashinasi':'Furgon',vehicleId:i<3?vehicles[i].id:null,driverId:i<3?drivers[i].id:null,loadingAt:i<3?stamp(i+1):null,status:['requested','assigned','arrived_for_loading','loading','departed','delivered'][i],createdAt:stamp(-5+i)}));
 const shipments=orders.slice(7,12).map((o,i)=>({id:`shipment_${i+1}`,shipmentNumber:`SH-2026-${String(i+1).padStart(4,'0')}`,orderId:o.id,transportRequestId:transportRequests[i+1]?.id||null,status:['planned','planned','loading','shipped','delivered'][i],shippedAt:i>=3?stamp(-2+i):null,deliveredAt:i===4?stamp(-1):null}));
 const inventoryMovements=products.slice(0,12).map((p,i)=>({id:`movement_${i+1}`,productId:p.id,warehouseId:p.warehouseId,type:'income',quantity:100+i*15,previousQuantity:p.quantity-100-i*15,newQuantity:p.quantity,referenceType:'purchase',referenceId:`seed-${i}`,userId:users[2].id,comment:'Boshlang‘ich demo harakati',createdAt:stamp(-30+i)}));
 const notifications=users.slice(1).flatMap((u,i)=>[{id:`notification_${i}`,userId:u.id,title:'Yangi zayavka navbatda',message:`${orders[i].orderNumber} zayavkasini ko‘rib chiqing.`,href:`/orders/${orders[i].id}`,readAt:null,createdAt:stamp(-i)}]);
 const auditLogs=orders.map((o,i)=>({id:`audit_${i}`,userId:users[i%5].id,userName:users[i%5].name,action:'order.created',entityType:'order',entityId:o.id,oldValue:null,newValue:{status:o.status},ip:'127.0.0.1',userAgent:'seed',source:'web',createdAt:o.createdAt}));
 const dailyStats=Array.from({length:30},(_,i)=>({date:stamp(i-29).slice(0,10),orders:2+(i*7%9),income:120+(i*13%90),outcome:80+(i*11%75)}));
 return {users,products,categories,warehouses,objects,orders,orderItems,inventoryMovements,reservations:[],shortages,supplyRequests,suppliers,invoices,transportRequests,vehicles,drivers,shipments,notifications,aiConversations:[],auditLogs,settings:[{key:'dailyStats',value:dailyStats},{key:'telegramLoginCodes',value:[]}]};
}
