import { v4 as uuid } from 'uuid';
import { AppError } from '../utils/errors.js';
import { audit, notify } from './audit.js';
export const transitions = { new:['checking','cancelled'], checking:['shortage','sent_to_supply','ready_for_picking','cancelled'], shortage:['sent_to_supply','checking','cancelled'], sent_to_supply:['supply_in_progress','checking','cancelled'], supply_in_progress:['checking','ready_for_picking','cancelled'], ready_for_picking:['picking','cancelled'], picking:['documents_ready','cancelled'], documents_ready:['waiting_transport','cancelled'], waiting_transport:['ready_for_loading','cancelled'], ready_for_loading:['loading','cancelled'], loading:['shipped','cancelled'], shipped:['delivered'], delivered:[], cancelled:[] };
const statusRoles={checking:['admin','warehouse','supply'],shortage:['admin','warehouse'],sent_to_supply:['admin','warehouse'],supply_in_progress:['admin','warehouse','supply'],ready_for_picking:['admin','warehouse','supply'],picking:['admin','warehouse'],documents_ready:['admin','warehouse'],waiting_transport:['admin','warehouse'],ready_for_loading:['admin','logistics'],loading:['admin','warehouse'],shipped:['admin','warehouse','logistics'],delivered:['admin','logistics'],cancelled:['admin','coordinator','warehouse']};
export const hasRole = (req, ...roles) => { if (!roles.includes(req.user.role)) throw new AppError('Bu amal uchun ruxsat yoʻq',403); };
export const getOrder = (db,id) => { const o = db.orders.find(x => x.id === id || x.orderNumber === id); if (!o) throw new AppError('Zayavka topilmadi',404); return o; };
export function changeStatus(db,req,order,status) { if (!transitions[order.status]?.includes(status)) throw new AppError(`${order.status} → ${status} holatiga oʻtish mumkin emas`,409); if(!statusRoles[status]?.includes(req.user.role))throw new AppError(`${status} holatini oʻzgartirishga ruxsat yoʻq`,403); const old=order.status; order.status=status; order.updatedAt=new Date().toISOString(); audit(db,req,'order.status', 'order',order.id,old,status); }
export function checkOrder(db,req,order) {
  if(['shortage','sent_to_supply','supply_in_progress'].includes(order.status))changeStatus(db,req,order,'checking');
  let missing=0;
  for (const item of db.orderItems.filter(x=>x.orderId===order.id)) {
    const p=db.products.find(x=>x.id===item.productId); if(!p) continue;
    const outstanding=item.requestedQuantity-(item.reservedQuantity||0); const available=Math.max(p.quantity-p.reservedQuantity,0); const reserve=Math.min(outstanding,available);
    if(reserve>0){p.reservedQuantity+=reserve;item.reservedQuantity=(item.reservedQuantity||0)+reserve;db.reservations.push({id:uuid(),orderId:order.id,orderItemId:item.id,productId:p.id,quantity:reserve,status:'active',createdAt:new Date().toISOString()});}
    item.shortageQuantity=Math.max(item.requestedQuantity-item.reservedQuantity,0);
    if(item.shortageQuantity>0){missing++; let shortage=db.shortages.find(s=>s.orderId===order.id&&s.productId===p.id&&s.status!=='resolved'); if(!shortage){shortage={id:uuid(),orderId:order.id,productId:p.id,requestedQuantity:item.requestedQuantity,availableQuantity:p.quantity-p.reservedQuantity,shortageQuantity:item.shortageQuantity,status:'open',createdAt:new Date().toISOString()};db.shortages.push(shortage);}
      if(!db.supplyRequests.some(s=>s.orderId===order.id&&s.productId===p.id&&!['received','cancelled'].includes(s.status))){db.supplyRequests.push({id:uuid(),requestNumber:`SR-${new Date().getFullYear()}-${String(db.supplyRequests.length+1).padStart(4,'0')}`,orderId:order.id,productId:p.id,requestedQuantity:item.shortageQuantity,availableQuantity:p.quantity-p.reservedQuantity,shortageQuantity:item.shortageQuantity,supplierId:null,purchasePrice:0,expectedDate:null,receivedDate:null,assignedTo:null,status:'new',comment:'Avtomatik zayavka tekshiruvidan yaratildi',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}
    }
  }
  if(missing){ if(order.status==='checking')changeStatus(db,req,order,'shortage'); if(order.status==='shortage')changeStatus(db,req,order,'sent_to_supply'); if(order.status==='sent_to_supply')changeStatus(db,req,order,'supply_in_progress'); notify(db,['supply'],'Yangi taʼminot ehtiyoji',`${order.orderNumber} uchun yetishmayotgan mahsulotlar bor.`,'/supply-requests'); }
  else { if(order.status==='checking'||order.status==='supply_in_progress'||order.status==='sent_to_supply'||order.status==='shortage')changeStatus(db,req,order,'ready_for_picking'); for(const s of db.shortages.filter(x=>x.orderId===order.id))s.status='resolved'; notify(db,['warehouse','coordinator'],'Zayavka yigʻishga tayyor',`${order.orderNumber} mahsulotlari rezerv qilindi.` ,`/orders/${order.id}`); }
  return {missing,items:db.orderItems.filter(x=>x.orderId===order.id)};
}
export function createInvoiceAndTransport(db,req,order){
  let invoice=db.invoices.find(x=>x.orderId===order.id); if(!invoice){const items=db.orderItems.filter(x=>x.orderId===order.id);const products=items.map(i=>db.products.find(p=>p.id===i.productId));const weight=items.reduce((s,i)=>s+(db.products.find(p=>p.id===i.productId)?.weight||0)*i.pickedQuantity,0);const volume=items.reduce((s,i)=>s+(db.products.find(p=>p.id===i.productId)?.volume||0)*i.pickedQuantity,0);invoice={id:uuid(),invoiceNumber:`NK-${new Date().getFullYear()}-${String(db.invoices.length+1).padStart(4,'0')}`,orderId:order.id,items:items.map(i=>({...i,product:db.products.find(p=>p.id===i.productId)})),weight,volume,status:'ready',createdAt:new Date().toISOString()};db.invoices.push(invoice);db.transportRequests.push({id:uuid(),requestNumber:`TR-${new Date().getFullYear()}-${String(db.transportRequests.length+1).padStart(4,'0')}`,orderId:order.id,objectId:order.objectId,weight,volume,quantity:items.reduce((s,i)=>s+i.pickedQuantity,0),recommendedVehicleType:weight>5000||volume>30?'Yuk mashinasi':'Furgon',vehicleId:null,driverId:null,loadingAt:null,status:'requested',createdAt:new Date().toISOString()});}
  return invoice;
}
